baseURL: "https://robertavaltorta.github.io" 
title: Roberta Rosa Valtorta
theme: PaperMod
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: 
enableEmoji: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv-valtorta.pdf
          weight: 1
        - name: Publications
          url: publications/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3

params:
    description: "PhD in Social Psychology"
    author: Roberta Rosa Valtorta
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["cv","publications","projects"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Roberta Rosa Valtorta
          subtitle: "Postdoctoral researcher at the University of Milano-Bicocca"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          #buttons:
            #- name: CV
              #url: cv-valtorta.pdf
            #- name: Publications
              #url: publications/
            #- name: Projects
              #url: projects/

    socialIcons:
        - name: Google Scholar
          url: https://scholar.google.it/citations?user=Cxtkt6cAAAAJ&hl=en
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Roberta-Valtorta
        - name: ORCID
          url: https://orcid.org/0000-0003-0565-5463
        - name: X
          url: https://x.com/valtortaroberta
        - name: Email
          url: mailto:roberta.valtorta@unimib.it
        - name: CV
          url: cv-valtorta.pdf
        
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Roberta Rosa Valtorta"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2