baseURL: "https://robertavaltorta.github.io" 
title: Roberta Rosa Valtorta
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: CV
          url: cv.pdf
          weight: 4

params:
    description: "PROVA"
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications","projects","teaching","CV"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Roberta Rosa Valtorta
          subtitle: "I am a "
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Projects
              url: projects/
            - name: Teaching
              url: teaching/
            - name: CV
              url: cv.pdf

    socialIcons:
        - name: Email
          url: mailto:roberta.valtorta@unimib.it
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: ResearchGate
          url: https://github.com/pmichaillat
        - name: ORCID
          url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Roberta Rosa Valtorta"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2